### PR TITLE
made it python3 compatible

### PR DESCRIPTION
**Pull request by braingineer**
the issues were:
- some print statements needed to have ()
- some dicts were using iteritems; changed to items
- some dicts.keys() and dicts.values() were being indexed; so I converted them to a list so they could be idexed
- 8bitwonder.ttf was all lowercase in file and all caps in file. made it consistent. 
- some divisions assumed int division. fixed the ones i could find (i.e. the ones that broke)

### CODE REVIEW

**Comment by Greenheart** [comment]
Thanks for your time! These seems to be some great improvements! :)

I'll just verify that everything works

**Comment by Greenheart** [comment]
@braingineer Great work! 

Just a curious question, how did you find this project? :)

**Comment by braingineer** [comment]
No problem =). 

I searched github for pygame and tanks, haha. 

I have a part-time position teaching courses at an extracurricular school for gifted kids.  I am teaching an AI course this session (in python3) and wanted to do a tank-based game.  I had needed some base code to visualize/build the AI scaffolding around.  However, most of the pygame tank games are bad.. or convoluted.  I liked your project! So I spent some time fixing it up =).

**Comment by Greenheart** [comment]
That's cool!

Good luck with the AI, I followed you so I can see what the result might look like :)

**Comment by braingineer** [comment]
Cool =). 

I'll be sure to ping you with the skeleton AI & when the kids flesh out their own AI.

**Pull request merged**
